name: Go
on: release
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [darwin, linux]
        arch: [amd64]
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o hashiman .

    - name: Add to release
      run: |
        sudo apt-get install jq
        FILENAME=hashiman_${{ matrix.os }}_${{ matrix.arch }}.zip
        zip $FILENAME ./hashiman
        UPLOAD_URL=$(curl https://api.github.com/repos/itsjxck/hashiman/releases/$GITHUB_REF | jq -r '.upload_url')
        UPLOAD_URL=${UPLOAD_URL/"{?name,label}"/?name=$FILENAME}
        AUTH_HEADER="Authorization: token ${GITHUB_TOKEN}"
        CONTENT_LENGTH_HEADER="Content-Length: $(stat -c%s "${FILENAME}")"
        CONTENT_TYPE_HEADER="Content-Type: application/zip"
        curl -sSL -XPOST -H "${AUTH_HEADER}" -H "${CONTENT_LENGTH_HEADER}" -H "${CONTENT_TYPE_HEADER}" --upload-file "${FILENAME}" "${UPLOAD_URL}"
